### PR TITLE
Add "Fork Me Banner"

### PR DESCRIPTION
**Pull request by prizov**
#3  "Fork Me Banner" added and format code

### CODE REVIEW

**Comment by prizov** [comment]
#3

**Comment by moonmeister** [comment]
@prizov did you confirm this works using `gatsby build`? From what I can see the index.html in the root is left over from the old site and will have no affect on the new gatsby site.

**Comment by M0nica** [comment]
+1 @moonmeister. It looks like you edited the wrong index file. Can you please confirm that this works on your end and then update your PR?

**Comment by moonmeister** [comment]
I actually just wrote a Gatsby plugin to do this, I need to fix an error but then it'll be ready if you want to use that to implement this feature. It's called gatsby-plugin-github-ribbon.

**Comment by moonmeister** [comment]
Okay the plugin is published and functional. 

https://www.npmjs.com/package/gatsby-plugin-github-ribbon

**Pull request closed without merging**
